### ISSUE TITLE
ModuleNotFoundError: No module named 'sonique.stable_audio_tools'

### ISSUE THREAD

**Issue by fakerybakery** [zxxwxyyy/sonique#1]
Hi,
Thanks for releasing SONIQUE!
I'm trying to run the inference code but I'm running into the error `ModuleNotFoundError: No module named 'sonique.stable_audio_tools'`.
I installed the SONIQUE package using `pip install git+https://github.com/zxxwxyyy/sonique`.
Full traceback:
```
  File "/home/user/app/app.py", line 1, in <module>
    from sonique import get_pretrained_model
  File "/usr/local/lib/python3.10/site-packages/sonique/__init__.py", line 1, in <module>
    from .stable_audio_tools.models.factory import create_model_from_config, create_model_from_config_path
ModuleNotFoundError: No module named 'sonique.stable_audio_tools'
```
Thanks!

**Comment by zxxwxyyy** [comment]
Hi, thank you for your interest in SONIQUE! I believe that's because the internal dependencies aren’t properly resolved when installed directly from the repo. Please try follow the [instruction](https://github.com/zxxwxyyy/sonique#install) to set up

**Comment by fakerybakery** [comment]
Hi,
Thanks for the tip - I was actually able to resolve the issue by copying the code files into my project directory - for some reason it looks like the stable audio tools module was not installed.
Sorry about the trouble!
